name: build-tokens
run-name: Build tokens for Flow Design System

on:
  push:
    paths:
      - src/figma/*
    branches-ignore:
      - main
  workflow_dispatch: {}

jobs:
  build-design-tokens:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_AUTHOR: Dheeraj Sayala
      CI_COMMIT_MESSAGE: building design tokens
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies, build tokens
        run: |
          yarn
          yarn run build-design-tokens
      - name: Commit and push
        run: |
          git config user.email "dheerosaur@gmail.com"
          git config user.name "Dheeraj Sayala"
          git commit -am "${{ env.CI_COMMIT_MESSAGE }}"
          git push
